jenkins:
  build: ./jenkins
  container_name: jenkins 
  restart: unless-stopped
  ports:
    - 8080:8080
  #net: 
  #environment:
  #  - username=[my-username]
  #  - password=[my-password]

resume:
  build: ./resume
  container_name: resume
  restart: unless-stopped
  ports: 
   - 80:3001
  #net: 
  #environment:
  #  - username=[my-username]
  #  - password=[my-password]
